package et.ut.einvoice.compliance;

import et.ut.einvoice.compliance.crypto.CryptoHealthState;
import et.ut.einvoice.compliance.crypto.DigitalSignatureProvider;
import et.ut.einvoice.compliance.signature.DevelopmentFiscalSignatureService;
import et.ut.einvoice.compliance.signature.FiscalSignatureResponse;
import et.ut.einvoice.compliance.signature.ProductionInsaFiscalSignatureService;
import et.ut.einvoice.government.domain.TenantGovernmentCredential;
import et.ut.einvoice.government.service.TenantGovernmentCredentialService;
import et.ut.einvoice.platform.exception.BusinessException;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@ActiveProfiles("test")
public class FiscalDigitalSignatureTestSuite {

    @Autowired
    private DevelopmentFiscalSignatureService devSignatureService;

    @Test
    @DisplayName("Stage 9: Real Digital Signature Generation - Non-hash output with metadata")
    void test_RealDigitalSignature_GeneratedWithMetadata() {
        UUID tenantId = UUID.randomUUID();
        String payload = "{\"irn\":\"IRN-TEST-123\",\"total\":5000.00,\"sellerTin\":\"0012345678\"}";

        FiscalSignatureResponse response = devSignatureService.signFiscalDocument(tenantId, payload, null);

        assertNotNull(response);
        assertNotNull(response.signature());
        assertFalse(response.signature().isBlank());

        // Digest must NOT equal signature (SHA-256 digest is 64 hex chars; RSA-2048 signature is 256 bytes Base64-encoded ~344 chars)
        assertNotEquals(response.documentDigest(), response.signature());
        assertTrue(response.signature().length() > 200, "RSA digital signature must be full cryptographic signature");

        // Verify metadata snapshot
        assertNotNull(response.certificateMetadata());
        assertNotNull(response.certificateMetadata().serialNumber());
        assertNotNull(response.signedTimestamp());
        assertEquals("SHA256withRSA", response.signingAlgorithm());
    }

    @Test
    @DisplayName("Stage 9: Signature Verification - Authenticates untampered payload")
    void test_SignatureVerification_UntamperedPayload_Succeeds() {
        UUID tenantId = UUID.randomUUID();
        String payload = "{\"documentNumber\":\"INV-001\",\"amount\":1200.50}";

        FiscalSignatureResponse response = devSignatureService.signFiscalDocument(tenantId, payload, null);

        boolean valid = devSignatureService.verifyFiscalSignature(tenantId, payload, response.signature(), null);
        assertTrue(valid, "Signature must verify against original untampered payload");
    }

    @Test
    @DisplayName("Stage 9: Tampered Payload - Verification fails closed")
    void test_SignatureVerification_TamperedPayload_Fails() {
        UUID tenantId = UUID.randomUUID();
        String originalPayload = "{\"documentNumber\":\"INV-001\",\"amount\":1200.50}";
        String tamperedPayload = "{\"documentNumber\":\"INV-001\",\"amount\":99999.50}";

        FiscalSignatureResponse response = devSignatureService.signFiscalDocument(tenantId, originalPayload, null);

        boolean valid = devSignatureService.verifyFiscalSignature(tenantId, tamperedPayload, response.signature(), null);
        assertFalse(valid, "Tampered payload must fail signature verification");
    }

    @Test
    @DisplayName("Stage 9: Tenant Key Isolation - Cross-tenant signature verification fails")
    void test_TenantIsolation_CrossTenantVerification_Fails() {
        UUID tenantA = UUID.randomUUID();
        UUID tenantB = UUID.randomUUID();
        String payload = "{\"documentNumber\":\"INV-001\",\"amount\":1200.50}";

        // Sign with Tenant A
        FiscalSignatureResponse responseA = devSignatureService.signFiscalDocument(tenantA, payload, null);

        // Verify with Tenant B's keys
        // First ensure Tenant B has generated keys
        devSignatureService.signFiscalDocument(tenantB, payload, null);

        boolean valid = devSignatureService.verifyFiscalSignature(tenantB, payload, responseA.signature(), null);
        assertFalse(valid, "Signature generated by Tenant A must not verify under Tenant B's key");
    }

    @Test
    @DisplayName("Stage 9: Production Mode Fails Closed - Refuses software fallback when HSM unavailable")
    void test_ProductionHsm_FailsClosed_WithoutHardware() {
        DigitalSignatureProvider mockHsmProvider = Mockito.mock(DigitalSignatureProvider.class);
        Mockito.when(mockHsmProvider.isHsmBacked()).thenReturn(true);
        Mockito.when(mockHsmProvider.getHealthStatus()).thenReturn(CryptoHealthState.HARDWARE_MISSING_EXTERNAL_DEPENDENCY);

        TenantGovernmentCredentialService mockCredService = Mockito.mock(TenantGovernmentCredentialService.class);
        UUID tenant = UUID.randomUUID();
        var cred = new TenantGovernmentCredentialService.DecryptedGovernmentCredentials(
                tenant, "SYS-01", "0012345678", "REG-01", "CID", "CSEC", "KEY",
                "INSA-CERT-01", "CERT-SERIAL-01", java.time.Instant.now().plusSeconds(86400 * 30),
                et.ut.einvoice.government.domain.CredentialStatus.ACTIVE
        );
        Mockito.when(mockCredService.getDecryptedCredentialsForTenant(tenant)).thenReturn(cred);

        ProductionInsaFiscalSignatureService prodService = new ProductionInsaFiscalSignatureService(
                mockHsmProvider, mockCredService
        );

        // Must fail closed with INSA_HSM_UNAVAILABLE without falling back to software keys
        BusinessException ex = assertThrows(BusinessException.class, () ->
                prodService.signFiscalDocument(tenant, "{\"invoice\":1}", null)
        );
        assertEquals("INSA_HSM_UNAVAILABLE", ex.getCode());
    }
}
